name:  Security CI   

on:  
  push:
    branches:
      - main
jobs:
  security-check:
    runs-on: ubuntu-latest
    
    steps:  
      - name: Check out repository
        uses: actions/checkout@v4
      
      - name: Run security gate simulation
        run: python3 app.py

      - name: Scan repository for secrets
        uses: gitleaks/gitleaks-action@v2

      - name: Install Bandit
        run: pip install bandit

      - name: Run SAST scan with Bandit
        run: bandit app.py 
          