name:  Security CI   

on:  
  push:
    branches:
      - main
jobs:
  security-check:
    runs-on: ubuntu-latest
    
    steps:  
      - name: Check out repository
        uses: actions/checkout@v4
      
      